spring:
  datasource:
    url: ${DB_JDBC_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  config:
    activate:
      on-profile: development

jwt:
  secret: ${JWT_SECRET_KEY}
  token-validity-in-milliseconds: 86400000    # 토큰 만료 시간, 1일

server:
  port: 8443
  ssl:
    key-store: ${KEY_STORE}
    key-store-password: ${KEY_STORE_PASSWORD}
    key-store-type: pkcs12
    key-alias: tomcat
    enabled: true

---
spring:
  datasource:
    url: ${RDS_JDBC_URL}
    username: ${RDS_DB_USER}
    password: ${RDS_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  config:
    activate:
      on-profile: production

jwt:
  secret: ${JWT_SECRET_KEY}
  token-validity-in-milliseconds: 86400000    # 토큰 만료 시간, 1일