cors:
  allowed-origins: "*"

---

spring:
  datasource:
    url: ${DB_JDBC_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  hikari:
    pool-name: jpa-hikari-pool
    maximum-pool-size: 10
    jdbc-url: ${DB_JDBC_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: ${spring.datasource.driver-class-name}
    data-source-properties:
      rewriteBatchedStatements: true
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        default_batch_fetch_size: ${chunkSize:100}
        jdbc.batch_size: 20
        order_inserts: true
        order_updates: true
        show_sql: true
        format_sql: true
        use_sql_comments: true
  config:
    activate:
      on-profile: development

jwt:
  secret: ${JWT_SECRET_KEY}
  token-validity-in-milliseconds: 86400000    # 토큰 만료 시간, 1일

---

spring:
  datasource:
    url: ${RDS_JDBC_URL}
    username: ${RDS_DB_USER}
    password: ${RDS_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  hikari:
    pool-name: jpa-hikari-pool
    maximum-pool-size: 5
    max-life-timeout: 86300
    jdbc-url: ${RDS_JDBC_URL}
    username: ${RDS_DB_USER}
    password: ${RDS_DB_PASSWORD}
    driver-class-name: ${spring.datasource.driver-class-name}
    data-source-properties:
      rewriteBatchedStatements: true
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        default_batch_fetch_size: ${chunkSize:100}
        jdbc.batch_size: 20
        order_inserts: true
        order_updates: true
    defer-datasource-initialization: true
  config:
    activate:
      on-profile: production

jwt:
  secret: ${JWT_SECRET_KEY}
  token-validity-in-milliseconds: 86400000    # 토큰 만료 시간, 1일